<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MyAcerSwift" failures="1" tests="1" name="Test" time="6.588" errors="0" timestamp="2023-07-19T06:29:52 BST">
  <testcase classname="testCases.TC003_LoginDataDrivenTest" name="test_loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.DataProviders.getData(DataProviders.java:25)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_loginDDT -->
</testsuite> <!-- Test -->
